name: tests

on:
  push:
    paths-ignore:
    - '*.md'
    branches: [ main ]
  pull_request:
    paths-ignore:
    - '*.md'
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-v2-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-v2-
            name: Build

    - uses: docker/build-push-action@v3
      with:
        push: false
        tags: |
             ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.GOOGLE_REPOSITORY }}/${{ secrets.GOOGLE_IMAGE }}:test